FROM ubuntu:20.10

RUN apt-get -y update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -y --no-install-recommends \
        awscli curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -L -o /usr/local/bin/kubectl https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl \
    && chmod a+x /usr/local/bin/kubectl

ADD ./bin/kgrid /usr/local/bin