/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/replicatedhq/kgrid/apis/kgrid/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTestResults implements TestResultInterface
type FakeTestResults struct {
	Fake *FakeKgridV1alpha1
	ns   string
}

var testresultsResource = schema.GroupVersionResource{Group: "kgrid", Version: "v1alpha1", Resource: "testresults"}

var testresultsKind = schema.GroupVersionKind{Group: "kgrid", Version: "v1alpha1", Kind: "TestResult"}

// Get takes name of the testResult, and returns the corresponding testResult object, and an error if there is any.
func (c *FakeTestResults) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TestResult, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(testresultsResource, c.ns, name), &v1alpha1.TestResult{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestResult), err
}

// List takes label and field selectors, and returns the list of TestResults that match those selectors.
func (c *FakeTestResults) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TestResultList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(testresultsResource, testresultsKind, c.ns, opts), &v1alpha1.TestResultList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TestResultList{ListMeta: obj.(*v1alpha1.TestResultList).ListMeta}
	for _, item := range obj.(*v1alpha1.TestResultList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested testResults.
func (c *FakeTestResults) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(testresultsResource, c.ns, opts))

}

// Create takes the representation of a testResult and creates it.  Returns the server's representation of the testResult, and an error, if there is any.
func (c *FakeTestResults) Create(ctx context.Context, testResult *v1alpha1.TestResult, opts v1.CreateOptions) (result *v1alpha1.TestResult, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(testresultsResource, c.ns, testResult), &v1alpha1.TestResult{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestResult), err
}

// Update takes the representation of a testResult and updates it. Returns the server's representation of the testResult, and an error, if there is any.
func (c *FakeTestResults) Update(ctx context.Context, testResult *v1alpha1.TestResult, opts v1.UpdateOptions) (result *v1alpha1.TestResult, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(testresultsResource, c.ns, testResult), &v1alpha1.TestResult{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestResult), err
}

// Delete takes name of the testResult and deletes it. Returns an error if one occurs.
func (c *FakeTestResults) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(testresultsResource, c.ns, name), &v1alpha1.TestResult{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTestResults) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(testresultsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TestResultList{})
	return err
}

// Patch applies the patch and returns the patched testResult.
func (c *FakeTestResults) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TestResult, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(testresultsResource, c.ns, name, pt, data, subresources...), &v1alpha1.TestResult{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TestResult), err
}
