/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/replicatedhq/kgrid/apis/kgrid/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGrids implements GridInterface
type FakeGrids struct {
	Fake *FakeKgridV1alpha1
	ns   string
}

var gridsResource = schema.GroupVersionResource{Group: "kgrid", Version: "v1alpha1", Resource: "grids"}

var gridsKind = schema.GroupVersionKind{Group: "kgrid", Version: "v1alpha1", Kind: "Grid"}

// Get takes name of the grid, and returns the corresponding grid object, and an error if there is any.
func (c *FakeGrids) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Grid, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gridsResource, c.ns, name), &v1alpha1.Grid{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Grid), err
}

// List takes label and field selectors, and returns the list of Grids that match those selectors.
func (c *FakeGrids) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GridList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gridsResource, gridsKind, c.ns, opts), &v1alpha1.GridList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GridList{ListMeta: obj.(*v1alpha1.GridList).ListMeta}
	for _, item := range obj.(*v1alpha1.GridList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested grids.
func (c *FakeGrids) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gridsResource, c.ns, opts))

}

// Create takes the representation of a grid and creates it.  Returns the server's representation of the grid, and an error, if there is any.
func (c *FakeGrids) Create(ctx context.Context, grid *v1alpha1.Grid, opts v1.CreateOptions) (result *v1alpha1.Grid, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gridsResource, c.ns, grid), &v1alpha1.Grid{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Grid), err
}

// Update takes the representation of a grid and updates it. Returns the server's representation of the grid, and an error, if there is any.
func (c *FakeGrids) Update(ctx context.Context, grid *v1alpha1.Grid, opts v1.UpdateOptions) (result *v1alpha1.Grid, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gridsResource, c.ns, grid), &v1alpha1.Grid{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Grid), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGrids) UpdateStatus(ctx context.Context, grid *v1alpha1.Grid, opts v1.UpdateOptions) (*v1alpha1.Grid, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gridsResource, "status", c.ns, grid), &v1alpha1.Grid{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Grid), err
}

// Delete takes name of the grid and deletes it. Returns an error if one occurs.
func (c *FakeGrids) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gridsResource, c.ns, name, opts), &v1alpha1.Grid{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGrids) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gridsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GridList{})
	return err
}

// Patch applies the patch and returns the patched grid.
func (c *FakeGrids) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Grid, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gridsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Grid{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Grid), err
}
