/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/replicatedhq/kgrid/apis/kgrid/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOutcomes implements OutcomeInterface
type FakeOutcomes struct {
	Fake *FakeKgridV1alpha1
	ns   string
}

var outcomesResource = schema.GroupVersionResource{Group: "kgrid", Version: "v1alpha1", Resource: "outcomes"}

var outcomesKind = schema.GroupVersionKind{Group: "kgrid", Version: "v1alpha1", Kind: "Outcome"}

// Get takes name of the outcome, and returns the corresponding outcome object, and an error if there is any.
func (c *FakeOutcomes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Outcome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(outcomesResource, c.ns, name), &v1alpha1.Outcome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Outcome), err
}

// List takes label and field selectors, and returns the list of Outcomes that match those selectors.
func (c *FakeOutcomes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.OutcomeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(outcomesResource, outcomesKind, c.ns, opts), &v1alpha1.OutcomeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.OutcomeList{ListMeta: obj.(*v1alpha1.OutcomeList).ListMeta}
	for _, item := range obj.(*v1alpha1.OutcomeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested outcomes.
func (c *FakeOutcomes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(outcomesResource, c.ns, opts))

}

// Create takes the representation of a outcome and creates it.  Returns the server's representation of the outcome, and an error, if there is any.
func (c *FakeOutcomes) Create(ctx context.Context, outcome *v1alpha1.Outcome, opts v1.CreateOptions) (result *v1alpha1.Outcome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(outcomesResource, c.ns, outcome), &v1alpha1.Outcome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Outcome), err
}

// Update takes the representation of a outcome and updates it. Returns the server's representation of the outcome, and an error, if there is any.
func (c *FakeOutcomes) Update(ctx context.Context, outcome *v1alpha1.Outcome, opts v1.UpdateOptions) (result *v1alpha1.Outcome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(outcomesResource, c.ns, outcome), &v1alpha1.Outcome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Outcome), err
}

// Delete takes name of the outcome and deletes it. Returns an error if one occurs.
func (c *FakeOutcomes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(outcomesResource, c.ns, name), &v1alpha1.Outcome{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOutcomes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(outcomesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.OutcomeList{})
	return err
}

// Patch applies the patch and returns the patched outcome.
func (c *FakeOutcomes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Outcome, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(outcomesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Outcome{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Outcome), err
}
