/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/replicatedhq/kgrid/apis/kgrid/v1alpha1"
	scheme "github.com/replicatedhq/kgrid/pkg/client/kgridclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ApplicationTestsGetter has a method to return a ApplicationTestInterface.
// A group's client should implement this interface.
type ApplicationTestsGetter interface {
	ApplicationTests(namespace string) ApplicationTestInterface
}

// ApplicationTestInterface has methods to work with ApplicationTest resources.
type ApplicationTestInterface interface {
	Create(ctx context.Context, applicationTest *v1alpha1.ApplicationTest, opts v1.CreateOptions) (*v1alpha1.ApplicationTest, error)
	Update(ctx context.Context, applicationTest *v1alpha1.ApplicationTest, opts v1.UpdateOptions) (*v1alpha1.ApplicationTest, error)
	UpdateStatus(ctx context.Context, applicationTest *v1alpha1.ApplicationTest, opts v1.UpdateOptions) (*v1alpha1.ApplicationTest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ApplicationTest, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ApplicationTestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApplicationTest, err error)
	ApplicationTestExpansion
}

// applicationTests implements ApplicationTestInterface
type applicationTests struct {
	client rest.Interface
	ns     string
}

// newApplicationTests returns a ApplicationTests
func newApplicationTests(c *KgridV1alpha1Client, namespace string) *applicationTests {
	return &applicationTests{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the applicationTest, and returns the corresponding applicationTest object, and an error if there is any.
func (c *applicationTests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ApplicationTest, err error) {
	result = &v1alpha1.ApplicationTest{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applicationtests").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ApplicationTests that match those selectors.
func (c *applicationTests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ApplicationTestList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ApplicationTestList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("applicationtests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested applicationTests.
func (c *applicationTests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("applicationtests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a applicationTest and creates it.  Returns the server's representation of the applicationTest, and an error, if there is any.
func (c *applicationTests) Create(ctx context.Context, applicationTest *v1alpha1.ApplicationTest, opts v1.CreateOptions) (result *v1alpha1.ApplicationTest, err error) {
	result = &v1alpha1.ApplicationTest{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("applicationtests").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationTest).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a applicationTest and updates it. Returns the server's representation of the applicationTest, and an error, if there is any.
func (c *applicationTests) Update(ctx context.Context, applicationTest *v1alpha1.ApplicationTest, opts v1.UpdateOptions) (result *v1alpha1.ApplicationTest, err error) {
	result = &v1alpha1.ApplicationTest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("applicationtests").
		Name(applicationTest.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationTest).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *applicationTests) UpdateStatus(ctx context.Context, applicationTest *v1alpha1.ApplicationTest, opts v1.UpdateOptions) (result *v1alpha1.ApplicationTest, err error) {
	result = &v1alpha1.ApplicationTest{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("applicationtests").
		Name(applicationTest.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(applicationTest).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the applicationTest and deletes it. Returns an error if one occurs.
func (c *applicationTests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applicationtests").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *applicationTests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("applicationtests").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched applicationTest.
func (c *applicationTests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ApplicationTest, err error) {
	result = &v1alpha1.ApplicationTest{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("applicationtests").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
