/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/replicatedhq/kgrid/apis/kgrid/v1alpha1"
	scheme "github.com/replicatedhq/kgrid/pkg/client/kgridclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GridsGetter has a method to return a GridInterface.
// A group's client should implement this interface.
type GridsGetter interface {
	Grids(namespace string) GridInterface
}

// GridInterface has methods to work with Grid resources.
type GridInterface interface {
	Create(ctx context.Context, grid *v1alpha1.Grid, opts v1.CreateOptions) (*v1alpha1.Grid, error)
	Update(ctx context.Context, grid *v1alpha1.Grid, opts v1.UpdateOptions) (*v1alpha1.Grid, error)
	UpdateStatus(ctx context.Context, grid *v1alpha1.Grid, opts v1.UpdateOptions) (*v1alpha1.Grid, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Grid, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GridList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Grid, err error)
	GridExpansion
}

// grids implements GridInterface
type grids struct {
	client rest.Interface
	ns     string
}

// newGrids returns a Grids
func newGrids(c *KgridV1alpha1Client, namespace string) *grids {
	return &grids{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the grid, and returns the corresponding grid object, and an error if there is any.
func (c *grids) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Grid, err error) {
	result = &v1alpha1.Grid{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grids").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Grids that match those selectors.
func (c *grids) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GridList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GridList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grids").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested grids.
func (c *grids) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("grids").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a grid and creates it.  Returns the server's representation of the grid, and an error, if there is any.
func (c *grids) Create(ctx context.Context, grid *v1alpha1.Grid, opts v1.CreateOptions) (result *v1alpha1.Grid, err error) {
	result = &v1alpha1.Grid{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("grids").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grid).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a grid and updates it. Returns the server's representation of the grid, and an error, if there is any.
func (c *grids) Update(ctx context.Context, grid *v1alpha1.Grid, opts v1.UpdateOptions) (result *v1alpha1.Grid, err error) {
	result = &v1alpha1.Grid{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grids").
		Name(grid.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grid).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *grids) UpdateStatus(ctx context.Context, grid *v1alpha1.Grid, opts v1.UpdateOptions) (result *v1alpha1.Grid, err error) {
	result = &v1alpha1.Grid{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grids").
		Name(grid.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(grid).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the grid and deletes it. Returns an error if one occurs.
func (c *grids) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grids").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *grids) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grids").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched grid.
func (c *grids) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Grid, err error) {
	result = &v1alpha1.Grid{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("grids").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
